# Generated by Django 2.0.2 on 2018-03-08 14:33

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_site', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='Profile Pictures/')),
                ('usr', models.OneToOneField(on_delete=django.contrib.auth.models.User, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
